-- Inserção de dados de exemplo para a tabela leads
-- Execute este script no Supabase SQL Editor

-- Primeiro, vamos obter alguns IDs de usuários para usar como responsáveis e criadores
-- Substitua pelos IDs reais dos usuários do seu sistema

INSERT INTO leads (
  nome,
  telefone,
  email,
  empresa,
  cargo,
  cidade,
  estado,
  produtos_interesse,
  origem,
  origem_detalhes,
  observacoes,
  status,
  responsavel,
  data_contato,
  proxima_acao,
  data_proxima_acao,
  criado_por
) VALUES 
(
  'Dr. Ricardo Almeida',
  '(11) 99123-4567',
  'ricardo.almeida@email.com',
  'Clínica Almeida',
  'Médico Cardiologista',
  'São Paulo',
  'SP',
  ARRAY['irpf', 'contabilidade_pj', 'auxilio_moradia'],
  'site',
  'Formulário de contato do site',
  'Médico interessado em serviços completos para PF e PJ',
  'novo',
  NULL, -- Será atribuído automaticamente
  NULL,
  'Realizar primeiro contato telefônico',
  '2024-01-25',
  (SELECT id FROM auth.users LIMIT 1) -- Usar o primeiro usuário como criador
),
(
  'Dra. Marina Santos',
  '(11) 98765-4321',
  'marina.santos@clinicasantos.com.br',
  'Clínica Santos Ltda',
  'Diretora Médica',
  'São Paulo',
  'SP',
  ARRAY['contabilidade_pj', 'recuperacao_tributaria_pj'],
  'indicacao',
  'Indicação do Dr. Carlos Mendes',
  'Clínica em crescimento, interessada em otimização tributária',
  'contatado',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-20 14:30:00',
  'Agendar reunião para apresentação de proposta',
  '2024-01-26',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dr. Paulo Henrique',
  '(11) 97777-8888',
  'paulo.henrique@email.com',
  NULL,
  'Médico Residente',
  'São Paulo',
  'SP',
  ARRAY['irpf', 'auxilio_moradia'],
  'redes_sociais',
  'Instagram - post sobre auxílio moradia',
  'Médico residente interessado em auxílio moradia e IRPF',
  'qualificado',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-18 10:15:00',
  'Enviar documentação necessária para auxílio moradia',
  '2024-01-27',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Hospital Regional S.A.',
  '(11) 2222-3333',
  'financeiro@hospitalregional.com.br',
  'Hospital Regional S.A.',
  'Gerente Financeiro',
  'São Paulo',
  'SP',
  ARRAY['contabilidade_pj', 'consultoria_tributaria', 'alteracao_pj'],
  'evento',
  'Feira de Saúde 2024 - Stand MedStaff',
  'Hospital de grande porte interessado em consultoria tributária',
  'proposta',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-15 16:00:00',
  'Aguardar retorno da proposta comercial',
  '2024-01-29',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dr. Fernando Lima',
  '(11) 96666-7777',
  'fernando.lima@email.com',
  'Consultório Dr. Lima',
  'Médico Ortopedista',
  'São Paulo',
  'SP',
  ARRAY['irpf', 'restituicao_previdenciaria_pf'],
  'google',
  'Pesquisa: "restituição previdenciária médicos"',
  'Médico aposentado interessado em revisão previdenciária',
  'negociacao',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-12 09:30:00',
  'Finalizar negociação de honorários',
  '2024-01-28',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dra. Ana Carolina',
  '(11) 95555-6666',
  'ana.carolina@email.com',
  'Clínica Bem Estar',
  'Médica Dermatologista',
  'São Paulo',
  'SP',
  ARRAY['contabilidade_pj', 'irpf'],
  'time_interno',
  'Indicação interna - equipe comercial',
  'Médica com clínica própria, cliente em potencial',
  'ganho',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-08 11:00:00',
  'Iniciar processo de onboarding',
  '2024-01-30',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dr. Roberto Silva',
  '(11) 94444-5555',
  'roberto.silva@email.com',
  NULL,
  'Médico Especialista',
  'São Paulo',
  'SP',
  ARRAY['auxilio_moradia'],
  'site',
  'Landing page - auxílio moradia',
  'Médico interessado apenas em auxílio moradia',
  'perdido',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-05 15:45:00',
  'Lead perdido - não atendeu mais as ligações',
  NULL,
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Clínica MedCenter',
  '(11) 3456-7890',
  'contato@medcenter.com.br',
  'Clínica MedCenter Ltda',
  'Administrador',
  'São Paulo',
  'SP',
  ARRAY['contabilidade_pj', 'recuperacao_tributaria_pj', 'alteracao_pj'],
  'indicacao',
  'Indicação de cliente atual',
  'Clínica com múltiplas unidades, grande potencial',
  'novo',
  NULL,
  NULL,
  'Realizar primeiro contato',
  '2024-01-31',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dr. Marcos Pereira',
  '(11) 93333-4444',
  'marcos.pereira@email.com',
  NULL,
  'Médico Residente',
  'São Paulo',
  'SP',
  ARRAY['irpf', 'auxilio_moradia'],
  'redes_sociais',
  'LinkedIn - post sobre benefícios médicos',
  'Médico residente em especialização',
  'contatado',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-22 13:20:00',
  'Agendar reunião para esclarecimentos',
  '2024-02-01',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Dra. Fernanda Costa',
  '(11) 92222-3333',
  'fernanda.costa@email.com',
  'Consultório Dra. Fernanda',
  'Médica Pediatra',
  'São Paulo',
  'SP',
  ARRAY['irpf', 'contabilidade_pj'],
  'outros',
  'Referência de contador anterior',
  'Médica com consultório próprio, migração de contador',
  'qualificado',
  (SELECT id FROM auth.users LIMIT 1),
  '2024-01-19 08:45:00',
  'Preparar proposta comercial personalizada',
  '2024-02-02',
  (SELECT id FROM auth.users LIMIT 1)
);

-- Verificar os dados inseridos
SELECT 
  id,
  nome,
  empresa,
  status,
  origem,
  produtos_interesse,
  proxima_acao,
  data_proxima_acao,
  created_at
FROM leads 
ORDER BY created_at DESC;