-- Inserção de dados de exemplo para a tabela pipelines
-- Execute este script no Supabase SQL Editor

INSERT INTO pipelines (
  tipo,
  lead_id,
  cliente_id,
  nome_cliente,
  email_cliente,
  telefone_cliente,
  servicos_interesse,
  estagio,
  proposta_comercial,
  proxima_acao,
  data_proxima_acao,
  responsavel,
  historico,
  status,
  motivo_perdido,
  observacoes
) VALUES 
(
  'captacao',
  NULL,
  'CLI-PIP-001',
  'Dr. André Martins',
  'andre.martins@email.com',
  '(11) 99876-5432',
  '["irpf", "contabilidade_pj", "auxilio_moradia"]'::jsonb,
  'captacao',
  NULL,
  'Agendar reunião de apresentação dos serviços',
  '2024-01-25',
  'Ana Costa',
  '[{"data": "2024-01-20", "acao": "Primeiro contato via telefone", "responsavel": "Ana Costa", "resultado": "Cliente interessado em conhecer os serviços"}]'::jsonb,
  'ativo',
  NULL,
  'Médico recém-formado, potencial para múltiplos serviços'
),
(
  'proposta',
  NULL,
  'CLI-PIP-002',
  'Clínica Vida Nova Ltda',
  'contato@vidanova.com.br',
  '(11) 3333-4444',
  '["contabilidade_pj", "recuperacao_tributaria_pj", "alteracao_pj"]'::jsonb,
  'proposta',
  '{"servicos": [{"nome": "Contabilidade PJ", "valor_mensal": 2500.00, "descricao": "Contabilidade completa para clínica"}, {"nome": "Recuperação Tributária", "valor_unico": 45000.00, "descricao": "Recuperação de tributos pagos indevidamente"}], "valor_total": 47500.00, "prazo_execucao": "6 meses", "forma_pagamento": "50% entrada + 5x"}'::jsonb,
  'Aguardar retorno da proposta comercial',
  '2024-01-30',
  'Pedro Santos',
  '[{"data": "2024-01-10", "acao": "Reunião inicial", "responsavel": "Pedro Santos", "resultado": "Levantamento das necessidades"}, {"data": "2024-01-15", "acao": "Envio da proposta", "responsavel": "Pedro Santos", "resultado": "Proposta enviada por email"}]'::jsonb,
  'ativo',
  NULL,
  'Clínica em expansão, boa oportunidade de negócio'
),
(
  'contrato',
  NULL,
  'CLI-PIP-003',
  'Dra. Carla Souza',
  'carla.souza@email.com',
  '(11) 98765-1234',
  '["irpf", "restituicao_previdenciaria_pf"]'::jsonb,
  'negociacao',
  '{"servicos": [{"nome": "IRPF", "valor_unico": 800.00, "descricao": "Declaração de Imposto de Renda PF"}, {"nome": "Restituição Previdenciária", "valor_unico": 12000.00, "descricao": "Revisão de aposentadoria especial"}], "valor_total": 12800.00, "desconto_aplicado": 5, "valor_final": 12160.00}'::jsonb,
  'Finalizar negociação e enviar contrato',
  '2024-01-28',
  'Ana Costa',
  '[{"data": "2024-01-05", "acao": "Primeiro contato", "responsavel": "Ana Costa", "resultado": "Cliente interessada"}, {"data": "2024-01-12", "acao": "Reunião técnica", "responsavel": "João Ferreira", "resultado": "Viabilidade confirmada"}, {"data": "2024-01-18", "acao": "Proposta apresentada", "responsavel": "Ana Costa", "resultado": "Solicitou desconto"}]'::jsonb,
  'ativo',
  NULL,
  'Médica aposentada, caso complexo mas rentável'
),
(
  'execucao',
  NULL,
  'CLI-PIP-004',
  'Hospital Regional S.A.',
  'financeiro@hospitalregional.com.br',
  '(11) 2222-3333',
  '["contabilidade_pj", "alteracao_pj", "consultoria_tributaria"]'::jsonb,
  'execucao',
  '{"servicos": [{"nome": "Contabilidade PJ", "valor_mensal": 8500.00, "descricao": "Contabilidade completa para hospital"}, {"nome": "Alteração PJ", "valor_unico": 3500.00, "descricao": "Alteração de capital social"}], "valor_contrato": 105500.00, "prazo_execucao": "12 meses"}'::jsonb,
  'Acompanhar execução dos serviços contratados',
  '2024-02-01',
  'Maria Oliveira',
  '[{"data": "2023-11-15", "acao": "Primeiro contato", "responsavel": "Pedro Santos", "resultado": "Interesse confirmado"}, {"data": "2023-12-01", "acao": "Proposta aprovada", "responsavel": "Pedro Santos", "resultado": "Contrato assinado"}, {"data": "2024-01-01", "acao": "Início da execução", "responsavel": "Maria Oliveira", "resultado": "Serviços iniciados"}]'::jsonb,
  'ganho',
  NULL,
  'Cliente estratégico, contrato de longo prazo'
),
(
  'captacao',
  NULL,
  'CLI-PIP-005',
  'Dr. Paulo Henrique',
  'paulo.henrique@email.com',
  '(11) 97777-8888',
  '["irpf", "auxilio_moradia"]'::jsonb,
  'qualificacao',
  NULL,
  'Realizar qualificação do lead',
  '2024-01-26',
  'Ana Costa',
  '[{"data": "2024-01-22", "acao": "Lead recebido via site", "responsavel": "Sistema", "resultado": "Lead capturado"}, {"data": "2024-01-23", "acao": "Primeiro contato telefônico", "responsavel": "Ana Costa", "resultado": "Agendada reunião de qualificação"}]'::jsonb,
  'ativo',
  NULL,
  'Médico jovem, potencial para crescimento futuro'
),
(
  'proposta',
  NULL,
  'CLI-PIP-006',
  'Clínica Especializada Ltda',
  'admin@especializada.com.br',
  '(11) 4444-5555',
  '["contabilidade_pj", "recuperacao_tributaria_pj"]'::jsonb,
  'fechamento',
  '{"servicos": [{"nome": "Contabilidade PJ", "valor_mensal": 3200.00, "descricao": "Contabilidade para clínica especializada"}, {"nome": "Recuperação Tributária", "valor_unico": 28000.00, "descricao": "Recuperação de PIS/COFINS"}], "valor_total": 66400.00, "prazo_execucao": "8 meses"}'::jsonb,
  'Aguardar assinatura do contrato',
  '2024-01-29',
  'Pedro Santos',
  '[{"data": "2024-01-08", "acao": "Reunião comercial", "responsavel": "Pedro Santos", "resultado": "Interesse confirmado"}, {"data": "2024-01-16", "acao": "Proposta enviada", "responsavel": "Pedro Santos", "resultado": "Em análise pelo cliente"}, {"data": "2024-01-24", "acao": "Follow-up", "responsavel": "Pedro Santos", "resultado": "Proposta aprovada verbalmente"}]'::jsonb,
  'ativo',
  NULL,
  'Clínica bem estruturada, decisão em breve'
);

-- Verificar os dados inseridos
SELECT 
  id,
  tipo,
  nome_cliente,
  estagio,
  status,
  responsavel,
  data_proxima_acao,
  proposta_comercial->>'valor_total' as valor_proposta
FROM pipelines 
ORDER BY data_proxima_acao ASC;