name: Debug Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test:unit
        
      - name: Build project
        run: npm run build
        
      - name: Check secrets availability
        run: |
          echo "🔍 Verificando secrets..."
          echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"
          echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        
      - name: Install Vercel CLI
        run: |
          echo "📦 Instalando Vercel CLI..."
          npm install -g vercel@latest
          vercel --version
        
      - name: Test Vercel login
        run: |
          echo "🔐 Testando login no Vercel..."
          vercel whoami --token $VERCEL_TOKEN || echo "❌ Falha no login"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        
      - name: List Vercel projects
        run: |
          echo "📋 Listando projetos Vercel..."
          vercel ls --token $VERCEL_TOKEN || echo "❌ Falha ao listar projetos"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy with verbose output
        run: |
          echo "🚀 Tentando deploy com output detalhado..."
          vercel --token $VERCEL_TOKEN --prod --yes --debug || echo "❌ Deploy falhou"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}