name: Test GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Simple test
        run: |
          echo "🎉 GitHub Actions está funcionando!"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"